#! /bin/sh
###################################################
#      		       COLORS                     #
###################################################
. "$HOME/dotfiles/scripts/colors"

###################################################
#                     SETTINGS                    #
###################################################
bspc config border_width           1
bspc config window_gap         	   2
bspc config top_padding        	   34
bspc config left_padding       	   0
bspc config bottom_padding    	   0
bspc config split_ratio        	   0.50
bspc config focus_follows_pointer  true
bspc config normal_border_color	   "$color0"
bspc config active_border_color	   "$color0"
bspc config focused_border_color   "$fg"
bspc config presel_feedback_color  "$color7"

bspc monitor -d 1 2 3 4 5
