#!/bin/bash

# Install pacman packages.
sudo pacman -Syu alsa-utils exfat-utils git go leafpad libinput mesa network-manager-applet networkmanager openvpn pip-install python reflector rxvt-unicode rofi stalonetray stow tmux terminus-font unzip wireless_tools xf86-video-nouveau xorg-server xorg-xinit xorg-xsetroot xorg-xrandr zip zsh

# Create dotfile symlinks.
cd ~
git clone https://github.com/nelsonong/dotfiles --depth=1
cd dotfiles
stow bspwm mpd mpv ncmpcpp neovim polybar sxhkd tmux xserver zsh
sudo stow scripts -t /usr/local/bin
cd ..

# Install powerline.
sudo pip install powerline-shell

# Install powerline fonts.
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts

# Install aurman.
git clone http://aur.archlinux.org/aurman-git.git
cd aurman-git
makepkg -si
cd ..
rm -rf aurman-git

# Install aur packages.
aurman -Syu bdf-tewi-git bspwm-git discord google-chrome mpd-git neovim-git ncmpcpp-git polybar-git qbittorrent-git ranger-git redshift-git siji-git spotify simplenote-electron-bin slock-git sxhkd-git tdrop-git ttf-ms-fonts

# Install Google Drive client.
go get -u github.com/odeke-em/drive/cmd/drive
