#!/bin/sh
## Install packages.
sudo pacman -Syu
sudo pacman -Syu xorg-minimal xorg-fonts xorg-fonts xset xsetroot terminus-font dejavu-fonts rxvt-unicode \
                 bspwm sxhkd neovim leafpad ranger mpv mpd rofi polybar stow git

## Symlink dotfiles.
git clone --depth 1 https://github.com/nelsonong/dotfiles
cd $HOME/dotfiles
stow bookmarks bspwm fonts homepage mpd mpv ncmpcpp neovim polybar sxhkd tmux xserver zsh
cd ..

